### ISSUE TITLE
ethstat : multiple interfaces, vlan tagged interfaces

### ISSUE THREAD

**Issue by ferreol** [perfwatcher/perfwatcher#56]
Hi 
I am diving into the ethstat plugin.

->is there a way to have multiple interface monitored ?
->I am using tagged vlan interfaces with , it does not seem supported. It supported is by the interface plugin, but the interfaces plugin is more limited.

regards,

Ferréol

**Comment by ymettier** [comment]
Hello,

The Perfwatcher team does not support Collectd plugins except the ones that we developped specifically for Perfwatcher and that are not part of Collectd from http://collectd.org. Of course, we try to help when we have knowledge on it. Sorry, for ethstat, you will have to ask Collectd users or developers (see on http://collectd.org and https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_ethstat).

If you manage to have the metrics you want in rrd files, we can help you for displaying them (e.g. help you write your own etc/definitions.local.php and maybe include your definitions in mainstream etc/definitions.php).

Regards,
Yves

**Comment by ferreol** [comment]
my bad, thought it was a collectd-pw plugin

sorry !
